<x-layouts.marketing :title="__('Data Collection & Usage') . ' \u2014 OT1-Pro'" :description="__('OT1-Pro Data Collection & Usage Policy — what data we collect, why, and how we use it.')">

    <section class="py-20 lg:py-28">
        <div class="mx-auto max-w-3xl px-6">
            <h1 class="text-4xl font-bold tracking-tight">{{ __('Data Collection & Usage') }}</h1>
            <p class="mt-4 text-sm text-zinc-500">{{ __('Last updated') }}: October 2, 2026</p>
            <p class="mt-2 text-sm text-zinc-500">{{ __('Effective date') }}: October 2, 2026</p>

            <div class="mt-12 space-y-10 text-zinc-600 dark:text-zinc-600">

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('1. Overview') }}</h2>
                    <p class="mt-3">{{ __('This document explains in detail what data OT1-Pro collects, why we collect it, and how we use it. It supplements our') }} <a href="{{ route('privacy') }}" class="text-emerald-600 hover:underline">{{ __('Privacy Policy') }}</a> {{ __('and') }} <a href="{{ route('terms') }}" class="text-emerald-600 hover:underline">{{ __('Terms of Service') }}</a>.{{ __(' For any questions, contact privacy@ot1-pro.com.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('2. Data We Collect') }}</h2>

                    <h3 class="text-base font-semibold text-zinc-800 dark:text-zinc-800 mt-5">{{ __('2.1 Account & Authentication Data') }}</h3>
                    <p class="mt-2">{{ __('When you create an account or sign in, we collect:') }}</p>
                    <ul class="mt-2 list-disc pl-5 space-y-1 text-sm">
                        <li>{{ __('Name and email address') }}</li>
                        <li>{{ __('Password hash (we never store plaintext passwords)') }}</li>
                        <li>{{ __('OAuth provider tokens if you sign in via Google (Google profile name, email)') }}</li>
                        <li>{{ __('IP address and user agent at time of registration/login') }}</li>
                    </ul>

                    <h3 class="text-base font-semibold text-zinc-800 dark:text-zinc-800 mt-5">{{ __('2.2 Connected Platform Data') }}</h3>
                    <p class="mt-2">{{ __('When you connect a social media account (Facebook, Instagram, WhatsApp, Telegram, TikTok, Email), we collect:') }}</p>
                    <ul class="mt-2 list-disc pl-5 space-y-1 text-sm">
                        <li>{{ __('OAuth access tokens and refresh tokens (encrypted at rest)') }}</li>
                        <li>{{ __('Page/account name, ID, profile picture, and metadata from the platform') }}</li>
                        <li>{{ __('Incoming messages, conversation threads, and sender metadata (name, ID, avatar)') }}</li>
                        <li>{{ __('Message timestamps, read status, delivery receipts') }}</li>
                        <li>{{ __('Contact profiles and conversation history') }}</li>
                    </ul>
                    <p class="mt-3 text-sm text-zinc-500">{{ __('We only request the minimum permissions required for inbox functionality. See our') }} <a href="{{ route('privacy') }}" class="text-emerald-600 hover:underline">{{ __('Privacy Policy') }}</a> {{ __('for platform-specific permission details.') }}</p>

                    <h3 class="text-base font-semibold text-zinc-800 dark:text-zinc-800 mt-5">{{ __('2.3 Usage & Analytics Data') }}</h3>
                    <p class="mt-2">{{ __('We automatically collect:') }}</p>
                    <ul class="mt-2 list-disc pl-5 space-y-1 text-sm">
                        <li>{{ __('Browser type, operating system, device information') }}</li>
                        <li>{{ __('IP address (for security and fraud prevention)') }}</li>
                        <li>{{ __('Pages visited, features used, actions performed within the app') }}</li>
                        <li>{{ __('Session duration and login frequency') }}</li>
                    </ul>

                    <h3 class="text-base font-semibold text-zinc-800 dark:text-zinc-800 mt-5">{{ __('2.4 AI Interaction Data') }}</h3>
                    <p class="mt-2">{{ __('When AI features are enabled:') }}</p>
                    <ul class="mt-2 list-disc pl-5 space-y-1 text-sm">
                        <li>{{ __('Message content sent to AI providers (Anthropic Claude, etc.) for reply generation') }}</li>
                        <li>{{ __('AI-generated response content') }}</li>
                        <li>{{ __('Lead scores and qualification data generated by AI') }}</li>
                        <li>{{ __('Voice note audio sent to transcription provider (Groq) when voice-note handling is enabled') }}</li>
                    </ul>
                    <p class="mt-2 text-sm text-zinc-500">{{ __('AI providers do not retain or train on your content per their data processing agreements.') }}</p>

                    <h3 class="text-base font-semibold text-zinc-800 dark:text-zinc-800 mt-5">{{ __('2.5 Billing & Payment Data') }}</h3>
                    <p class="mt-2">{{ __('Handled by our payment processor Paddle:') }}</p>
                    <ul class="mt-2 list-disc pl-5 space-y-1 text-sm">
                        <li>{{ __('Name, email, billing address') }}</li>
                        <li>{{ __('Payment method details (card, bank transfer — handled entirely by Paddle)') }}</li>
                        <li>{{ __('Subscription plan, billing history, invoices') }}</li>
                    </ul>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('3. Why We Collect This Data') }}</h2>
                    <ul class="mt-3 list-disc pl-5 space-y-2 text-sm">
                        <li><strong>{{ __('Service Delivery:') }}</strong> {{ __('To fetch, display, and send messages across connected platforms') }}</li>
                        <li><strong>{{ __('AI Features:') }}</strong> {{ __('To generate reply suggestions, auto-responses, lead scoring, and transcription') }}</li>
                        <li><strong>{{ __('Analytics:') }}</strong> {{ __('To show conversation volume, response times, team performance') }}</li>
                        <li><strong>{{ __('Security:') }}</strong> {{ __('To detect fraud, unauthorized access, and abuse') }}</li>
                        <li><strong>{{ __('Compliance:') }}</strong> {{ __('To meet legal obligations and platform policy requirements') }}</li>
                        <li><strong>{{ __('Improvement:') }}</strong> {{ __('To develop new features and optimize performance') }}</li>
                        <li><strong>{{ __('Communication:') }}</strong> {{ __('To send transactional emails (password resets, billing, critical updates)') }}</li>
                    </ul>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('4. Data Sharing') }}</h2>
                    <p class="mt-3">{{ __('We share data only as follows:') }}</p>
                    <ul class="mt-3 list-disc pl-5 space-y-2 text-sm">
                        <li><strong>{{ __('Platform APIs:') }}</strong> {{ __('With Meta, Telegram, TikTok, email servers — only to provide inbox functionality') }}</li>
                        <li><strong>{{ __('AI Providers:') }}</strong> {{ __('Message content to Anthropic Claude for AI replies — opt-in, can be disabled') }}</li>
                        <li><strong>{{ __('Payment Processor:') }}</strong> {{ __('Billing data to Paddle (Merchant of Record) — we never see card details') }}</li>
                        <li><strong>{{ __('Infrastructure:') }}</strong> {{ __('Cloud providers under data processing agreements') }}</li>
                        <li><strong>{{ __('Legal:') }}</strong> {{ __('When required by law, court order, or to protect rights/safety') }}</li>
                    </ul>
                    <p class="mt-4 font-medium text-zinc-700 dark:text-zinc-700">{{ __('We do not sell, rent, or trade your data or your customers\' data to any third party for marketing purposes.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('5. Data Retention') }}</h2>
                    <p class="mt-3">{{ __('Account data: retained while account is active.') }}</p>
                    <p class="mt-2">{{ __('Conversation data: retained indefinitely for inbox history, but you can delete individual conversations or your entire account at any time.') }}</p>
                    <p class="mt-2">{{ __('OAuth tokens: deleted immediately when you disconnect a platform.') }}</p>
                    <p class="mt-2">{{ __('Message history: retained up to 30 days after account/platform deletion before permanent removal.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('6. Your Rights') }}</h2>
                    <p class="mt-3">{{ __('You have the right to:') }}</p>
                    <ul class="mt-3 list-disc pl-5 space-y-2 text-sm">
                        <li>{{ __('Access your personal data') }}</li>
                        <li>{{ __('Request correction of inaccurate data') }}</li>
                        <li>{{ __('Request deletion of your data ("right to be forgotten")') }}</li>
                        <li>{{ __('Export your data in machine-readable format') }}</li>
                        <li>{{ __('Object to processing for certain purposes') }}</li>
                        <li>{{ __('Withdraw consent by disconnecting platforms at any time') }}</li>
                    </ul>
                    <p class="mt-3">{{ __('To exercise these rights, email privacy@ot1-pro.com. We respond within 30 days.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('7. Meta Data Deletion Callback') }}</h2>
                    <p class="mt-3">{{ __('If you connected via Facebook/Instagram and want all data removed, you can:') }}</p>
                    <ul class="mt-3 list-disc pl-5 space-y-2 text-sm">
                        <li>{{ __('Use Facebook\'s Data Deletion Request at') }} <a href="https://www.facebook.com/help/contact/365599491808767" class="text-emerald-600 hover:underline" target="_blank" rel="noopener">{{ __('Facebook \u2192 Settings \u2192 Apps & Websites') }}</a></li>
                        <li>{{ __('Email us at') }} <a href="mailto:privacy@ot1-pro.com" class="text-emerald-600 hover:underline">privacy@ot1-pro.com</a> {{ __('with subject "Data Deletion Request"') }}</li>
                    </ul>
                    <p class="mt-3 text-sm">{{ __('This triggers our Meta Data Deletion Callback endpoint, which removes the connected account, contact profile, conversations, messages, and lead score events linked to your Facebook/Instagram identifier within 30 days.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('8. Cookies') }}</h2>
                    <p class="mt-3">{{ __('We use only essential session cookies to maintain authentication. No advertising, tracking, or third-party analytics cookies.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('9. Contact') }}</h2>
                    <p class="mt-3">{{ __('For questions about data collection:') }}</p>
                    <div class="mt-3 text-sm">
                        <p><strong>{{ __('Email:') }}</strong> privacy@ot1-pro.com</p>
                        <p class="mt-1"><strong>{{ __('Website:') }}</strong> https://ot1-pro.com/data-collection</p>
                    </div>
                </div>

            </div>
        </div>
    </section>

</x-layouts.marketing>