<x-layouts.marketing :title="__('Terms of Service') . ' — One Inbox'" :description="__('One Inbox Terms of Service — the rules and guidelines for using our platform.')">

    <section class="py-20 lg:py-28">
        <div class="mx-auto max-w-3xl px-6">
            <h1 class="text-4xl font-bold tracking-tight">{{ __('Terms of Service') }}</h1>
            <p class="mt-4 text-sm text-zinc-500">{{ __('Last updated') }}: {{ date('F j, Y') }}</p>

            <div class="mt-12 space-y-8 text-zinc-600 dark:text-zinc-400">
                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('1. Acceptance of Terms') }}</h2>
                    <p class="mt-3">{{ __('By accessing or using One Inbox, you agree to be bound by these Terms of Service. If you do not agree, please do not use our service.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('2. Description of Service') }}</h2>
                    <p class="mt-3">{{ __('One Inbox provides a unified social media inbox with AI-powered sales automation. We aggregate conversations from connected platforms and provide AI assistance for responding to messages.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('3. User Responsibilities') }}</h2>
                    <p class="mt-3">{{ __('You are responsible for maintaining the confidentiality of your account, complying with platform-specific terms (Meta, Telegram), and ensuring your use of AI responses complies with applicable laws and regulations.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('4. AI-Generated Content') }}</h2>
                    <p class="mt-3">{{ __('AI responses are generated automatically and may not always be accurate. You are ultimately responsible for all messages sent through your connected accounts, including those generated by AI.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('5. Subscription and Billing') }}</h2>
                    <p class="mt-3">{{ __('Certain features require a paid subscription. Billing terms, including pricing and renewal policies, are presented during the subscription process.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('6. Limitation of Liability') }}</h2>
                    <p class="mt-3">{{ __('One Inbox is provided "as is" without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('7. Termination') }}</h2>
                    <p class="mt-3">{{ __('We may terminate or suspend your account if you violate these terms. You may cancel your account at any time through your account settings.') }}</p>
                </div>

                <div>
                    <h2 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">{{ __('8. Contact') }}</h2>
                    <p class="mt-3">{{ __('For questions about these terms, contact us at legal@oneinbox.app.') }}</p>
                </div>
            </div>
        </div>
    </section>

</x-layouts.marketing>
